package com.example;
import org.json.JSONObject;
import java.util.Hashtable;

public class Methods {
    //how to get the rate in USD
    public static double getRate(String from, String to) throws Exception {
        String url = "https://openexchangerates.org/api/latest.json?app_id=4b24349366cd472aba59aaa865090eec&symbols=" + to;
        String json = Api.getData(url);
        JSONObject obj = new JSONObject(json);
        JSONObject rates = obj.getJSONObject("rates");
        double rate = rates.getDouble(to);
        return rate;
    }
    //a table of all the countries so it gives you the right notation for the currency
      public static Hashtable<String, String> getCountryCurrencyDict() {
    Hashtable<String, String> dict = new Hashtable<>();
     dict.put("united states", "USD");
        dict.put("philippines", "PHP");
        dict.put("japan", "JPY");
        dict.put("china", "CNY");
        dict.put("india", "INR");
        dict.put("united kingdom", "GBP");
        dict.put("germany", "EUR");
        dict.put("france", "EUR");
        dict.put("italy", "EUR");
        dict.put("spain", "EUR");
        dict.put("canada", "CAD");
        dict.put("australia", "AUD");
        dict.put("brazil", "BRL");
        dict.put("russia", " RUB");
        dict.put("south africa", "ZAR");
        dict.put("mexico", "MXN");
        dict.put("south korea", "KRW");
        dict.put("singapore", "SGD");
        dict.put("thailand", "THB");
        dict.put("malaysia", "MYR");
        dict.put("switzerland", "CHF");
        dict.put("sweden", "SEK");
        dict.put("norway", "NOK");
        dict.put("denmark", "DKK");
        dict.put("netherlands", "EUR");
        dict.put("belgium", "EUR");
        dict.put("austria", "EUR");
        dict.put("finland", "EUR");
        dict.put("portugal", "EUR");
        dict.put("greece", "EUR");
        dict.put("ireland", "EUR");
        dict.put("new zealand", "NZD");
        dict.put("turkey", "TRY");
        dict.put("saudi arabia", "SAR");
        dict.put("united arab emirates", "AED");
        dict.put("hong kong", "HKD");
        dict.put("taiwan", "TWD");
        dict.put("indonesia", "IDR");
        dict.put("pakistan", "PKR");
        dict.put("bangladesh", "BDT");
        dict.put("egypt", "EGP");
        dict.put("nigeria", "NGN");
        dict.put("poland", "PLN");
        dict.put("czech republic", "CZK");
        dict.put("hungary", "HUF");
        dict.put("romania", "RON");
        dict.put("chile", "CLP");
        dict.put("argentina", "ARS");
        dict.put("colombia", "COP");
        dict.put("peru", "PEN");
        dict.put("israel", "ILS");
        dict.put("south africa", "ZAR");
        dict.put("kenya", "KES");
        dict.put("morocco", "MAD");
        dict.put("philippines", "PHP");
        dict.put("vietnam", "VND");
        dict.put("malaysia", "MYR");
        dict.put("singapore", "SGD");
        dict.put("thailand", "THB");
        dict.put("switzerland", "CHF");
        dict.put("ukraine", "UAH");
        dict.put("croatia", "EUR");
        dict.put("serbia", "RSD");
        dict.put("bulgaria", "BGN");
        dict.put("slovakia", "EUR");
        dict.put("slovenia", "EUR");
        dict.put("estonia", "EUR");
        dict.put("latvia", "EUR");      
        dict.put("lithuania", "EUR");
        dict.put("iceland", "ISK");
        dict.put("euro", "EUR");
        dict.put("europe", "EUR");
        dict.put("uganda", "UGX");
        dict.put("zambia", "ZMW");
        dict.put("zimbabwe", "ZWL");
        dict.put("afghanistan", "AFN");
        dict.put("albania", "ALL");
        dict.put("algeria", "DZD");
        dict.put("angola", "AOA");
        dict.put("argentina", "ARS");
        dict.put("chad", "XAF");
        dict.put("chile", "CLP");
        dict.put("cuba", "CUP");
        dict.put("dominican republic", "DOP");
        dict.put("ecuador", "USD");
        dict.put("el salvador", "USD");
        dict.put("iran", "IRR");
        dict.put("iraq", "IQD");
        dict.put("jordan", "JOD");
        dict.put("kazakhstan", "KZT");
    return dict;
}
}
